### ISSUE TITLE
Tab name isn't entirely readable in non-compact mode

### ISSUE THREAD

**Issue by umarhamzy** [ZweTyy/Tokyo-Night-Moon-Theme-Zen-browser#1]
![image](https://github.com/user-attachments/assets/683a54a7-b0c4-44f1-8666-e216669d6a43)

I'd suggest a lighter shade of the navy blue colour (the colour from when you hover on other tabs) for the background, and the current bright purple for active tabs

**Comment by ZweTyy** [comment]
Can you clarify further what the problem is with the tabname not being entirely readable in non compact mode?
![240918_15h50m51s_screenshot](https://github.com/user-attachments/assets/46f6e643-3d3f-4cd5-8411-ac19862e0e5f)
However I added the purple for active tabs.

**Comment by umarhamzy** [comment]
It appears you might be on the previous version, in which case it actually is more readable. However the contrast ratio is still pretty low. As you can see here. https://colourcontrast.cc/?background=085e5a&foreground=ffffff

I would suggest improving the colour schematics such that the ratio is slightly higher, ideally above 4
My suggestion: https://colourcontrast.cc/?background=33394f&foreground=ffffff (same as tab hover colour)

**Comment by ZweTyy** [comment]
I am on the version that is on the theme store.
The background color I use for the tooltip is #1e2030

![image](https://github.com/user-attachments/assets/686d5bde-2b27-49cc-b1c6-a36bd07aa6f3)

And it has a contrast of 16.10
Or am I misunderstanding?

**Comment by umarhamzy** [comment]
I get where you're coming from. However, I'm talking about the active tab itself, which has the bright purple as the background and white text on it.

**Comment by ZweTyy** [comment]
Ah, I think I get it.
The purple in the active tab itself is too bright right?
![image](https://github.com/user-attachments/assets/a13604b5-e6fb-4fbe-bd9e-f3c032c126fc)

**Comment by umarhamzy** [comment]
You're absolutely correct, I just realized the link I sent earlier shows the wrong colours. My bad.

**Comment by ZweTyy** [comment]
Got it, will fix it in a bit

**Comment by ZweTyy** [comment]
I will proceed with #6C598C.
![image](https://github.com/user-attachments/assets/0cd601dc-c2ff-4ac6-8a54-87305c57cae7)
